import { NextResponse } from 'next/server';
import { isConfigAccessDenied, requireConfigAccess } from '@/lib/config-access';
import { getStats } from '@/lib/stats-service';

/**
 * Legacy compatibility endpoint.
 *
 * XP/point awards are generated by server-side actions. Older clients still
 * call this endpoint after some mutations, so return current authenticated
 * stats without trusting amount or partnerId from the request body.
 */
export async function PUT(request: Request) {
  try {
    const access = await requireConfigAccess(request);
    if (isConfigAccessDenied(access)) return access.response;

    return NextResponse.json(await getStats(access.configId));
  } catch (error) {
    console.error('Error refreshing XP:', error);
    return NextResponse.json({ error: 'Failed to refresh XP' }, { status: 500 });
  }
}
